// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/concourse/atc/api/containerserver"
	"github.com/concourse/atc/db"
)

type FakeContainerDB struct {
	GetContainerStub        func(handle string) (db.ContainerInfo, bool, error)
	getContainerMutex       sync.RWMutex
	getContainerArgsForCall []struct {
		handle string
	}
	getContainerReturns struct {
		result1 db.ContainerInfo
		result2 bool
		result3 error
	}
	ContainersStub        func(db.ContainerIdentifier) ([]db.ContainerInfo, bool, error)
	containersMutex       sync.RWMutex
	containersArgsForCall []struct {
		arg1 db.ContainerIdentifier
	}
	containersReturns struct {
		result1 []db.ContainerInfo
		result2 bool
		result3 error
	}
}

func (fake *FakeContainerDB) GetContainer(handle string) (db.ContainerInfo, bool, error) {
	fake.getContainerMutex.Lock()
	fake.getContainerArgsForCall = append(fake.getContainerArgsForCall, struct {
		handle string
	}{handle})
	fake.getContainerMutex.Unlock()
	if fake.GetContainerStub != nil {
		return fake.GetContainerStub(handle)
	} else {
		return fake.getContainerReturns.result1, fake.getContainerReturns.result2, fake.getContainerReturns.result3
	}
}

func (fake *FakeContainerDB) GetContainerCallCount() int {
	fake.getContainerMutex.RLock()
	defer fake.getContainerMutex.RUnlock()
	return len(fake.getContainerArgsForCall)
}

func (fake *FakeContainerDB) GetContainerArgsForCall(i int) string {
	fake.getContainerMutex.RLock()
	defer fake.getContainerMutex.RUnlock()
	return fake.getContainerArgsForCall[i].handle
}

func (fake *FakeContainerDB) GetContainerReturns(result1 db.ContainerInfo, result2 bool, result3 error) {
	fake.GetContainerStub = nil
	fake.getContainerReturns = struct {
		result1 db.ContainerInfo
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeContainerDB) Containers(arg1 db.ContainerIdentifier) ([]db.ContainerInfo, bool, error) {
	fake.containersMutex.Lock()
	fake.containersArgsForCall = append(fake.containersArgsForCall, struct {
		arg1 db.ContainerIdentifier
	}{arg1})
	fake.containersMutex.Unlock()
	if fake.ContainersStub != nil {
		return fake.ContainersStub(arg1)
	} else {
		return fake.containersReturns.result1, fake.containersReturns.result2, fake.containersReturns.result3
	}
}

func (fake *FakeContainerDB) ContainersCallCount() int {
	fake.containersMutex.RLock()
	defer fake.containersMutex.RUnlock()
	return len(fake.containersArgsForCall)
}

func (fake *FakeContainerDB) ContainersArgsForCall(i int) db.ContainerIdentifier {
	fake.containersMutex.RLock()
	defer fake.containersMutex.RUnlock()
	return fake.containersArgsForCall[i].arg1
}

func (fake *FakeContainerDB) ContainersReturns(result1 []db.ContainerInfo, result2 bool, result3 error) {
	fake.ContainersStub = nil
	fake.containersReturns = struct {
		result1 []db.ContainerInfo
		result2 bool
		result3 error
	}{result1, result2, result3}
}

var _ containerserver.ContainerDB = new(FakeContainerDB)
